title: Cingmen Research and Documentation
description: An empirical and systematic repository focused on modern web development and technical documentation.
baseurl: ""
url: "https://cingmen.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-remote-theme