title: Cingmen | Blog
email: cingmen@gmail.com
description: >-
  Digital Creator & Developer. Building cool things on the web.
baseurl: "" 
url: "https://cingmen.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed