title: Cingmen | Blog
email: cingmen@gmail.com
description: >-
  Digital Creator & Developer. Building cool things on the web.
baseurl: "" 
url: "https://cingmen.github.io"

# Build settings
remote_theme: pages-themes/minimal@v0.2.0 # Standard GitHub engine
plugins:
  - jekyll-remote-theme