title: "Joesavat Donovan - Cybersecurity & IT Professional"
description: "Engineering secure Information Technology infrastructure, constructing minimalist digital interfaces, and exploring new technological paradigms."
url: "https://cingmen.github.io"
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-remote-theme